services:
  slack2teams:
    build: .
    env_file:
      - .env
    volumes:
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
      - ./src:/app/src
      - ./${SLACK_EXPORT_PATH}:/app/${SLACK_EXPORT_PATH}
      - ./${USER_MIGRATIONS_PATH}:/app/${USER_MIGRATIONS_PATH}
      - ./state:/app/state
    command: bash
